### PR TITLE
Finish features after all scenarios in feature are done

### PR DESCRIPTION
**Pull request by ksami**
Finish the feature item once all scenarios in the feature are done, instead of finishing all features on test run complete

### CODE REVIEW

**Comment by filland** [comment]
@Kayuaga @vadimromanyak could your plz review the PR ?

**Comment by vadimromanyak** [comment]
@filland Changes look good to me.

Were there any issues spotted when finishing all features on test run complete?

**Comment by ksami** [comment]
Finishing all features on test run complete caused all the features to report the same duration taken to complete. For real-time visualisation, it would also wrongly show that the feature is still running even after it has completed.

**Comment by Kayuaga** [comment]
@filland  Look fine

**Comment by filland** [comment]
@Kayuaga @vadimromanyak thanks, guys

**Pull request merged**
