### PR TITLE
Revert "Use Before/After test item types"

### PR DESCRIPTION
**Pull request by filland**
Reverts reportportal/agent-js-cucumber#17

### CODE REVIEW

**Comment by ksami** [comment]
Can I know why this was reverted?

**Comment by filland** [comment]
@ksami hello, i accidentally merged your PR. Could you please create a new PR ?

**Comment by ksami** [comment]
I was mistaken, this revert was not actually merged into master yet so I can't create a new PR.

**Comment by filland** [comment]
@ksami there should be another way to create create that PR

**Comment by ksami** [comment]
I have created a revert for this at #21 in order to create a new PR to apply this

**Comment by filland** [comment]
@ksami look, it is already in master ?
https://github.com/reportportal/agent-js-cucumber/blob/39959da3e7de2e0e268e52a27e25f33c01a7c5fc/modules/cucumber-epam-reportportal-handler.js#L275

**Comment by ksami** [comment]
I was referring to this
> @ksami hello, i accidentally merged your PR. Could you please create a new PR ?

I must have misunderstood then, sorry for the confusion

**Comment by filland** [comment]
@ksami all right

**Pull request closed without merging**
